---
- name: install and configure tomcat
  hosts: appserver
  become: yes
  tasks:
    - name: update package and install java
      apt:
        name: "{{ java_package}}"
        update_cache: yes
        state: present
    - name: add a user tomcat
      user:
        name: "{{ tomcat_username}}"
        shell: "{{ tomcat_shell}}"
        home: "{{ tomcat_home }}"
        state: present
    - name: Download tomcat package
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "apache-tomcat-{{ tomcat_version }}.tar.gz"
    - name: untar the package
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home }}"
        remote_src: yes
    - name: create symblink
      file:
        src: "{{ tomact_home }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_home }}/latest"
        state: link
    - name: give ownership to tomcat user and group
      file:
        path: "{{ tomacat_ home }}"
        state: directory
        recurse: yes
        owner: "{{ tomacat_ username }}"
        group: "{{tomcat_username }}"
    - name: find the all shell files in the binaries
      find:
        path: "{{ tomcat_home }}/latest/bin"
        pattern: "*.sh"
      register: shfiles
    - set_fact:
        tomcat_executables: "{{shfiles.files | map(attributes='path') | list }}"
    - name: change permission of shell files
      file:
        path: "{{ item }}"
        mode: 0751
      with_items: "{{ tomcat_executables }}"
    - name: create tomcat service file
      copy:
        src: tomcat.service
        dest: "{{ tomcat_service_dest }}"
      notify:
        - reload and enable tomcat
    - name: ensure tomcat is running
      systemd:
        name: tomcat.service
        state: started
    - name: copy tomcat user files
      copy:
        src: files/tomcat_user.xml
        dest: "{{ tomcat_users_config_location }}"
    - name: copy manager context files
      copy:
        src: files/manager_context.xml
        dest: "{{ tomcat_manager_config_location }}"
    - name: copy host context files
      copy:
        src: files/host_manager_context.xml
        dest: "{{ tomcat_host_manager_config_location }}"
      notify: reload and enable tomcat
  handlers:
    - name: reload and enable tomcat
      systemd:
        name: tomcat.service
        daemon_reload: yes
        enable: yes
        state: restarted
